image: node:7.7.1

cache:
  paths:
  - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
  - npm run build
  - mkdir ./public 
  - cp -r ./docs/ ./public
  artifacts:
    paths:
    - public
  only:
  - master
