language: node_js

cache:
  yarn: true
  directories:
    - $HOME/.cpus
  
#  directories:
#    - elm-stuff/packages

before_install:
  # Install sysconfcpus
  # Reference: https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
  - |
    export PATH=$HOME/.cpus/bin:$PATH;
    if ! hash sysconfcpus 2>/dev/null; then
      git clone --depth=1 https://github.com/obmarg/libsysconfcpus.git "$HOME/libsysconfcpus";
      cd "$HOME/libsysconfcpus";
      ./configure --prefix="$HOME/.cpus";
      make -j2 install;
    fi
  # Prepare working directory
  - cd "$TRAVIS_BUILD_DIR"

# Install dependencies
install:
  - sysconfcpus -n 2 yarn install

# Build
script:
  - cp -rfv static/ app
  - rm -rfv app/bower_components
  - ls -al app &&
  - cp -rvf src/web/bower_components app/bower_components
  - echo "content of app/bower_components"
  - ls -al app/bower_components
  - echo "content of app/bower_components/paper-styles/element-styles/"
  - ls -al app/bower_components/paper-styles/element-styles/
#  - cross-env NODE_ENV=production webpack -p --progress &&
  - cd app
  - pwd
  - polymer --version
  - echo "polymer build in"
  - pwd
  - polymer build
  - echo "content of app/bower_components/paper-styles/element-styles/"
  - ls -al app/bower_components/paper-styles/element-styles/
  - exit 1
#  - sysconfcpus -n 2 yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
