language: node_js

env:
  - RELEASE_TAG_REGEX="^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"

cache:
  yarn: true
  directories:
    - $HOME/.cpus
    - $TRAVIS_BUILD_DIR/node_modules

# this applies to tags too
#branches:
#  only:
#    - master

#  directories:
#    - elm-stuff/packages

before_install:
  # Install sysconfcpus
  # Reference: https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
  - |
    export PATH=$HOME/.cpus/bin:$PATH;
    if ! hash sysconfcpus 2>/dev/null; then
      git clone --depth=1 https://github.com/obmarg/libsysconfcpus.git "$HOME/libsysconfcpus";
      cd "$HOME/libsysconfcpus";
      ./configure --prefix="$HOME/.cpus";
      make -j2 install;
    fi
  # Prepare working directory
  - cd "$TRAVIS_BUILD_DIR"
  - export PATH=./node_modules/.bin:$PATH

# Install dependencies
install:
    - sysconfcpus -n 2 yarn install
#    - echo "skip install"
#    - echo $TRAVIS_TAG

# Build
script:
  - run travis:build
#  - sysconfcpus -n 2 yarn build
#  - sysconfcpus -n 2 yarn build-dev
#  - echo "skip build"

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    local_dir: docs
    on:
      condition: "$TRAVIS_TAG =~ $RELEASE_TAG_REGEX && $TRAVIS_PULL_REQUEST = 'false'"
      tags: true

  - provider: script
    skip_cleanup: true
    script: run travis:deploy
    on:
      tags: true
      all_branches: true

