language: node_js

env:
  - RELEASE_TAG_REGEX="^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"

cache:
  yarn: true
  directories:
    - $HOME/.cpus

branches:
  only:
    - master

#  directories:
#    - elm-stuff/packages

before_install:
  # Install sysconfcpus
  # Reference: https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
  - |
    export PATH=$HOME/.cpus/bin:$PATH;
    if ! hash sysconfcpus 2>/dev/null; then
      git clone --depth=1 https://github.com/obmarg/libsysconfcpus.git "$HOME/libsysconfcpus";
      cd "$HOME/libsysconfcpus";
      ./configure --prefix="$HOME/.cpus";
      make -j2 install;
    fi
  # Prepare working directory
  - cd "$TRAVIS_BUILD_DIR"

# Install dependencies
install:
#    - sysconfcpus -n 2 yarn install
    - echo "skip install"
    - echo $TRAVIS_TAG

# Build
script:
#  - sysconfcpus -n 2 yarn build
#  - sysconfcpus -n 2 yarn build-dev
  - echo "skip build"

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: docs
    on:
      condition: "$TRAVIS_TAG =~ $RELEASE_TAG_REGEX && $TRAVIS_PULL_REQUEST = 'false'"
      tags: true

#  - provider: script
#    skip_cleanup: true
#    script: ./node_modules/.bin/run travis:deploy:prod
#    on:
#      condition: "$TRAVIS_TAG =~ $RELEASE_TAG_REGEX && $TRAVIS_PULL_REQUEST = 'false'"
#      tags: true
#
#  - provider: script
#    skip_cleanup: true
#    script: ./node_modules/.bin/run travis:deploy:dev
#    on:
#      branch: master
#      tags: false


