language: node_js

env:
  - RELEASE_TAG_REGEX="^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"

cache:
  yarn: true
  directories:
    - $HOME/.cpus

#branches:
#  only:
#    - master

#  directories:
#    - elm-stuff/packages

before_install:
  # Install sysconfcpus
  # Reference: https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
  - |
    export PATH=$HOME/.cpus/bin:$PATH;
    if ! hash sysconfcpus 2>/dev/null; then
      git clone --depth=1 https://github.com/obmarg/libsysconfcpus.git "$HOME/libsysconfcpus";
      cd "$HOME/libsysconfcpus";
      ./configure --prefix="$HOME/.cpus";
      make -j2 install;
    fi
  # Prepare working directory
  - cd "$TRAVIS_BUILD_DIR"

# Install dependencies
install:
    - sysconfcpus -n 2 yarn install
#  - npm install elm@0.18.0
#  - npm run install-elm

# Build
script:
  - sysconfcpus -n 2 yarn build
  - sysconfcpus -n 2 yarn build-dev

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: docs
    on:
      branch: master
      condition: "$TRAVIS_TAG =~ $RELEASE_TAG_REGEX && $TRAVIS_PULL_REQUEST = 'false' "

  - provider: script
    skip_cleanup: true
    script: ./node_modules/.bin/firebase deploy --project prod --public docs --token $FIREBASE_TOKEN_PROD
    on:
      branch: master
      condition: "$TRAVIS_TAG =~ $RELEASE_TAG_REGEX && $TRAVIS_PULL_REQUEST = 'false' "

  - provider: script
      skip_cleanup: true
      script: ./node_modules/.bin/firebase deploy --project dev --public dev --token $FIREBASE_TOKEN_DEV
      on:
        branch: master

