language: node_js

cache:
  yarn: true
  directories:
    - $HOME/.cpus
  
#  directories:
#    - elm-stuff/packages

before_install:
  # Install sysconfcpus
  # Reference: https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
  - |
    export PATH=$HOME/.cpus/bin:$PATH;
    if ! hash sysconfcpus 2>/dev/null; then
      git clone --depth=1 https://github.com/obmarg/libsysconfcpus.git "$HOME/libsysconfcpus";
      cd "$HOME/libsysconfcpus";
      ./configure --prefix="$HOME/.cpus";
      make -j2 install;
    fi
  # Prepare working directory
  - cd "$TRAVIS_BUILD_DIR"

# Install dependencies
install:
  - sysconfcpus -n 2 yarn install

# Build
script:
  - sysconfcpus -n 2 yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN_DEV
  project: "dev"
  on:
      branch: master

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN_PROD
  project: "prod"
  on:
      branch: master
