language: node_js
node_js:
  - "5"
install:
  - npm install -g elm
  - npm install -g elm-test
  - elm-package install -y
  - pushd tests && elm-package install -y && popd
script:
  - cd tests && elm-test Main.elm